# permissions for end users to view autoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-demo
    app.kubernetes.io/managed-by: kustomize
  name: autoservice-viewer-role
rules:
- apiGroups:
  - batch.modc.com
  resources:
  - autoservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.modc.com
  resources:
  - autoservices/status
  verbs:
  - get
