---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.modc.com
  resources:
  - autoservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.modc.com
  resources:
  - autoservices/finalizers
  verbs:
  - update
- apiGroups:
  - batch.modc.com
  resources:
  - autoservices/status
  verbs:
  - get
  - patch
  - update
