apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
  volumes:
  - name: project-volume
    projected:
      sources:
      - secret:
          name: app-secret
          items:
            - key: username
              path:
      - configMap:
          name: myconfigmap