apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-gpu-7
  namespace: kubevirt
spec:
  running: true
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: gpu-h100-02
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: "nvidia.com/gpu-h100"
          operator: "Exists"
          value: ""
          effect: "NoSchedule"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
      domain:
        devices:
          gpus:
            - deviceName: nvidia.com/GH100_H100_SXM5_80GB
              name: gpu1
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: harddrive-windows
            - disk:
                bus: virtio
              name: cloudinit
        machine:
          type: q35
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
      volumes:
        - containerDisk:
            image: images.neolink-ai.com/admin/win:10
          name: harddrive-windows
        - cloudInitConfigDrive:
            userDataBase64: I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiBUcnVlCnVzZXJzOgogIC0gbmFtZTogYWRtaW4KICAgIGxvY2tfcGFzc3dkOiBmYWxzZQogICAgcGxhaW5fdGV4dF9wYXNzd2Q6IHphcTExcWF6MjAyNAogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAo=
          name: cloudinit