apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/selected-node: gpu-3090-10
  name: win10-consumer-virtio
  namespace: kubevirt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "openebs-localpv-kubevirt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/selected-node: gpu-3090-10
  name: win10-consumer-iso
  namespace: kubevirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "openebs-localpv-kubevirt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/selected-node: gpu-3090-10
  name: win10-bus-iso
  namespace: kubevirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "openebs-localpv-kubevirt"