apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-gpu
  namespace: kubevirt
spec:
  running: true
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: gpu-h100-02
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: "nvidia.com/gpu-h100"
          operator: "Exists"
          value: ""
          effect: "NoSchedule"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
      domain:
        gpus:
          - deviceName: nvidia.com/GH100_H100_SXM5_80GB
            name: gpu1
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi   # 增加内存上限到 4Gi，避免超出限制
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          rng: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: images.neolink-ai.com/admin/fedora-cloud-container-disk-demo:devel
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk