apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-ubuntu-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "openebs-localpv"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: cdromiso
              disk:
                bus: sata
            - name: cloudinit
              disk:
                bus: sata
            - name: snapshot.yaml-ubuntu-data
              disk:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 4G
      networks:
        - name: default
          pod: {}
      volumes:
        - name: cdromiso
          persistentVolumeClaim:
            claimName: ubuntu-iso
        - name: snapshot.yaml-ubuntu-data
          persistentVolumeClaim:
            claimName: snapshot.yaml-ubuntu-data-pvc
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire:False }
          name: cloudinit