apiVersion: v1
kind: Service
metadata:
  namespace: echo-server
  name: echo-server-service
spec:
  selector:
    app: node-echo-server
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
      targetPort: 8080
  type: NodePort
  