apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win2022-server-winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-localpv
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2022-server-new
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2022-server
        kubevirt.io/os: windows
    spec:
      domain:
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        cpu:
          cores: 4
        devices:
          disks:
            - bootOrder: 1
              cdrom:
                bus: sata
              name: win2022-server-cdromiso
            - disk:
                bus: virtio
              name: win2022-server-harddrive
              bootOrder: 2
            - cdrom:
                bus: sata
              name: win2022-server-virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        # firmware:
        #   bootloader:
        #     efi:
        #       secureBoot: true
      volumes:
        - name: win2022-server-cdromiso
          persistentVolumeClaim:
            claimName: win2022-server-isohd
        - name: win2022-server-harddrive
          persistentVolumeClaim:
            claimName: win2022-server-winhd
        - containerDisk:
            image: kubevirt/virtio-container-volume
          name: win2022-server-virtiocontainerdisk