---
# ServiceAccount: cicd-service-account
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cicd-namespace
  name: "cicd-service-account"

---
# Role: cicd
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cicd-namespace
  name: cicd
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---
# RoleBinding: cicd-binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cicd-namespace
  name: cicd-binding
subjects:
  - kind: ServiceAccount
    name: "cicd-service-account"
    namespace: cicd-namespace
    apiGroup: ""
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io