apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "openebs-localpv"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-docker
spec:
  dataVolumeTemplates:
    - metadata:
        name: system-pvc
      spec:
        pvc:
          accessModes:
            - ReadWriteOncek
          resources:
            requests:
              storage: 50Gi
          storageClassName: openebs-localpv
          volumeMode: Filesystem
        source:
          registry:
            url: docker://harbor.123.125.194.106.nip.io:10443/kubevirt1/ubuntu22.04lts@sha256:5a9b884025861c3888e885b18c21f3311dd15a9ae6195fbc2e94a03dcf809d31
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - name: system-pvc
              disk:
                bus: virtio
            - name: ubuntu-data-pvc
              disk:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: "4"
            memory: 4Gi
          limits:
            cpu: "4"
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: system-pvc
          dataVolume:
            name: system-pvc
        - name: ubuntu-data-pvc
          persistentVolumeClaim:
            claimName: data-pvc