apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-smartclone-test
  labels:
    vmName: ubuntu-smartclone-test
    sshtest: "true"
spec:
  dataVolumeTemplates:
    - metadata:
        name: smart-clone-pvc
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: openebs-lvmpv
        source:
          pvc:
            name: ubuntu2204-ori
            namespace: default
  running: true
  template:
    metadata:
      labels:
        vmName: ubuntu-smartclone-test
        sshtest: "true"
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: datavolumevolume
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: datavolumevolume
          persistentVolumeClaim:
            claimName: smart-clone-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm1
              ssh_pwauth: True
              disable_root: false
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3/+8MsqMLimRFpRpnvhTo+J8oTK2TeBh+ZoJlpsjL8M6YHWAgLR5jSuO3ABugmISW2n4KK3V79UF1mOL70zhCIg0L7JJm/Ic/ytyR95n5ZvsQyPWEHgBHWbxgd2WLisp9PYfKo7Zl94AzaGjcNey0FP3ZcjqLnj01FPc4sOqTpq9ap9eKGklLTE5NTOlUwt+fbQYG7tuH9x5SKu4PhW40y2uvIe59hKqccmz1GPwJY4KoFtzA3wdc/TrCSryVkFsHseMlYjiPymGVH9N+QrO56au2YPA1p725YsfJi0tIM8NOC48UXpodiquGKwIYXuczRuXZ14hPU7z5+dpKYhnvh0hp8QEcS2VFRexAzUct2sSMkSYA35n9Od2u+6zc06ScFzV/sCWYLrQXuXE1JHnV0KlPmAKJVKoAEupl9c3J2i1/pL7aZlQnKb81FrDo8ITyNOX2d5FJfUERHoAc6qtwFEJaGPJFBKkkWhknj0GkbI8Dw6tD0MFRVZB4Q6C87pk= root@template
              chpasswd:
                list: |
                  ubuntu:ubuntu
                expire: False