apiVersion: batch.modc.com/v1
kind: Autoservice
metadata:
  labels:
    app.kubernetes.io/name: controller-demo
    app.kubernetes.io/managed-by: kustomize
  name: autoservice-sample
spec:
  # TODO(user): Add fields here
