---
#configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: "My App"
  APP_ENV: "PRODUCTION"

---
#secretes.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username: bXl1c2Vy
  password: bXlwYXNzd29yZA==

---
#PeristentVolume.yaml
apiVerrsion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/app

---
#PersistentVolumeClaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
          #configMap
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_NAME
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_ENV
          #secret
          - name: USRENAEM
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: password


        volumeMounts:
          - name: app-storage
            mountPath: /usr/share/nginx/html
          - name: config-volume
            mountPath: /etc/config
          - name: secret-volume
            mountPath: /etc/secret
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
        - name: config-volume
          configMap:
            name: app-config
        - name: secret-volume
          secret:
            secretName: app-secret



