apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-fedora2
  labels:
    expose: me2
spec:
  hostname: "myvmi2"
  subdomain: "mysubdomain2"
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-registry-disk-demo:latest
    - cloudInitNoCloud:
        userDataBase64: IyEvYmluL2Jhc2gKZWNobyAiZmVkb3JhOmZlZG9yYSIgfCBjaHBhc3N3ZAo=
      name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: mysubdomain2
spec:
  selector:
    expose: me2
  clusterIP: None
  ports:
    - name: foo # Actually, no port is needed.
      port: 1234
      targetPort: 1234