apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snap2pvctest
spec:
  storageClassName: openebs-lvmpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: file-generator-pod
spec:
  containers:
    - name: file-generator
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          # 生成多个 200MB 的大文件
          for i in $(seq 1 3); do
            dd if=/dev/urandom of=/data/largefile_$i bs=1M count=2000
          done
          # 保持 Pod 一直运行
          tail -f /dev/null
      volumeMounts:
        - mountPath: /data
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: snap2pvctest
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snap2pvctest-pvc-snapshot-1
  namespace: default
spec:
  source:
    persistentVolumeClaimName: snap2pvctest
  volumeSnapshotClassName: lvmpv-snapclass