version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongoDemo
    restart: always
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root