apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testubuntu
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testubuntu
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 4G
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: harbor.43.143.130.168.nip.io:30443/kubevirt/ubuntu-with-docker@sha256:b6fb0d233605a480357623d711491026dc7e67b14c635ec451aec57c1c591f76